name: dartboard
version: "0.1.0"
authors:
- TrainerGuy22 <zeusintraining@gmail.com>
description: A simple IRC bouncer written in Dart, with most functionality provided through plugins.
homepage: https://github.com/DirectMyFile/irc.dart/
environment:
  sdk: '>=1.2.0'
dependencies:
  event_dispatcher: '>=0.0.5 <0.1.0'
  ini: '0.0.6'