name: wabbit
version: 0.1.0
authors:
- TrainerGuy22 <zeusintraining@gmail.com>
- samrg472 <samrg472@gmail.com>
description: A simple IRC bouncer written in Dart, with most functionality provided through plugins.
homepage: https://github.com/wabbitbnc
environment:
  sdk: '>=1.5.8'
dependencies:
  args: '>=0.12.0 <0.13.0'
  event_dispatcher: '>=0.1.0 <0.2.0'
  plugins: '>=1.0.1 <2.0.0'
dev_dependencies:
  grinder: '>=0.5.4 <0.6.0'
