name: dartboard
version: "0.1.0"
authors:
- TrainerGuy22 <zeusintraining@gmail.com>
description: A simple IRC bouncer written in Dart, with most functionality provided through plugins.
homepage: https://github.com/DirectMyFile/dartboard/
environment:
  sdk: '>=1.2.0'
dependencies:
  event_dispatcher: '>=0.0.5 <0.1.0'
  yaml: "0.9.0"
  args: ">=0.11.0+1 <0.12.0"
